#==============================================================================
# ■ Gestion_Talents
# Pokemon Script Project - Krosk 
# Gestion_Talents - Damien Linux
# 13/01/2020
#-----------------------------------------------------------------------------
# Modulable
#-----------------------------------------------------------------------------
# Attribution des ID des talents aux clés d'exécution des talents
#-----------------------------------------------------------------------------
module POKEMON_S
  ID_ABILITY = {
                  1 => :puanteur, # PUANTEUR
                  2 => :crachin, # CRACHIN
                  3 => :turbo, # TURBO
                  4 => :armurbaston, # ARMURBASTON
                  5 => :fermete, # FERMETE
                  6 => :moiteur, # MOITEUR
                  7 => :echauffement, # ECHAUFFEMENT
                  8 => :voile_sable, # VOILE SABLE
                  9 => :statik, # STATIK
                  10 => :absorb_volt, # ABSORB VOLT
                  11 => :absorb_eau, # ABSORB EAU
                  12 => :benet, # BENET
                  13 => :ciel_gris, # CIEL GRIS
                  14 => :oeil_compose, # OEIL COMPOSE
                  15 => :insomnia, # INSOMNIA
                  16 => :deguisement, # DEGUISEMENT
                  17 => :vaccin, # VACCIN
                  18 => :torche, # TORCHE
                  19 => :ecran_poudre, # ECRAN POUDRE
                  20 => :tempo_perso, # TEMPO PERSO
                  21 => :ventouse, # VENTOUSE
                  22 => :intimidation, # INTIMIDATION
                  23 => :marque_ombre, # MARQUE OMBRE
                  24 => :peau_dure, # PEAU DURE
                  25 => :garde_mystik, # GARDE MYSTIK
                  26 => :levitation, # LEVITATION
                  27 => :pose_spore, # POSE SPORE
                  28 => :synchro, # SYNCHRO
                  29 => :corps_sain, # CORPS SAIN
                  30 => :medic_nature, # MEDIC NATURE
                  31 => :paratonnerre, # PARATONNERRE
                  32 => :serenite, # SERENITE
                  33 => :glissade, # GLISSADE
                  34 => :chlorophyle, # CHLOROPHYLE
                  35 => :lumiatirance, # LUMIATIRANCE
                  36 => :calque, # CALQUE
                  37 => :coloforce, # COLOFORCE
                  38 => :point_poison, # POINT POISON
                  39 => :attention, # ATTENTION
                  40 => :armumagma, # ARMUMAGMA
                  41 => :ignifu_voile, # IGNIFU-VOILE
                  42 => :magnepiege, # MAGNEPIEGE
                  43 => :anti_bruit, # ANTI-BRUIT
                  44 => :cuvette, # CUVETTE
                  45 => :sable_volant, # SABLE VOLANT
                  46 => :pression, # PRESSION
                  47 => :isograisse, # ISOGRAISSE
                  48 => :matinal, # MATINAL
                  49 => :corps_ardent, # CORPS ARDENT
                  50 => :fuite, # FUITE
                  51 => :regard_vif, # REGARD VIF
                  52 => :hyper_cutter, # HYPER CUTTER
                  53 => :ramassage, # RAMASSAGE
                  54 => :absenteisme, # ABSENTEISME
                  55 => :agitation, # AGITATION
                  56 => :joli_sourire, # JOLI SOURIRE
                  57 => :plus, # PLUS
                  58 => :minus, # MINUS
                  59 => :meteo, # METEO
                  60 => :glue, # GLUE
                  61 => :mue, # MUE
                  62 => :cran, # CRAN
                  63 => :ecaille_spe, # ECAILLE SPE.
                  64 => :suintement, # SUINTEMENT
                  65 => :engrais, # ENGRAIS
                  66 => :brasier, # BRASIER
                  67 => :torrent, # TORRENT
                  68 => :essaim, # ESSAIM
                  69 => :tete_de_roc, # TETE DE ROC
                  70 => :secheresse, # SECHERESSE
                  71 => :piege_sable, # PIEGE SABLE
                  72 => :esprit_vital, # ESPRIT VITAL
                  73 => :ecran_fumee, # ECRAN FUMEE
                  74 => :force_pure, # FORCE PURE
                  75 => :coque_armure, # COQUE ARMURE
                  76 => :cacophonie, # CACOPHONIE
                  77 => :air_lock, # AIR LOCK
                  78 => :pieds_confus, # PIEDS CONFUS
                  79 => :motorise, # MOTORISE
                  80 => :rivalite, # RIVALITE
                  81 => :impassible, # IMPASSIBLE
                  82 => :rideau_neige, # RIDEAU NEIGE
                  83 => :gloutonnerie, # GLOUTONNERIE
                  84 => :colerique, # COLERIQUE
                  85 => :delestage, # DELESTAGE
                  86 => :ignifuge, # IGNIFUGE
                  87 => :simple, # SIMPLE
                  88 => :peau_seche, # PEAU SECHE
                  89 => :telecharge, # TELECHARGE
                  90 => :poing_de_fer, # POING DE FER
                  91 => :soin_poison, # SOIN POISON
                  92 => :adaptabilite, # ADAPTABILITE
                  93 => :multi_coups, # MULTI-COUPS
                  94 => :hydratation, # HYDRATATION
                  95 => :force_soleil, # FORCE SOLEIL
                  96 => :pied_veloce, # PIED VELOCE
                  97 => :normalise, # NORMALISE
                  98 => :sniper, # SNIPER
                  99 => :garde_magik, # GARDE MAGIK
                  100 => :annule_garde, # ANNULE GARDE
                  101 => :frein, # FREIN
                  102 => :technicien, # TECHNICIEN
                  103 => :feuil_garde, # FEUIL. GARDE
                  104 => :maladresse, # MALADRESSE
                  105 => :brise_moule, # BRISE MOULE
                  106 => :chanceux, # CHANCEUX
                  107 => :boom_final, # BOOM FINAL
                  108 => :anticipation, # ANTICIPATION
                  109 => :prediction, # PREDICTION
                  110 => :inconscient, # INCONSCIENT
                  111 => :lentiteintee, # LENTITEINTEE
                  112 => :filtre, # FILTRE
                  113 => :debut_calme, # DEBUT CALME
                  114 => :querelleur, # QUERELLEUR
                  115 => :lavabo, # LAVABO
                  116 => :corps_gel, # CORPS GEL
                  117 => :solide_roc, # SOLIDE ROC
                  118 => :alerte_neige, # ALERTE NEIGE
                  119 => :cherche_miel, # CHERCHE MIEL
                  120 => :fouille, # FOUILLE
                  121 => :temeraire, # TEMERAIRE
                  122 => :multi_type, # MULTI-TYPE
                  123 => :don_floral, # DON FLORAL
                  124 => :mauvais_reve, # MAUVAIS REVE
                  125 => :acharne, # ACHARNÉ
                  126 => :analyste, # ANALYSTE
                  127 => :armurouillee, # ARMUROUILLÉE
                  128 => :baigne_sable, # BAIGNE SABLE
                  129 => :coeur_de_coq, # COEUR DE COQ
                  130 => :coeur_noble, # COEUR NOBLE
                  131 => :coeur_soin, # COEUR SOIN
                  132 => :contestation, # CONTESTATION
                  133 => :corps_maudit, # CORPS MAUDIT
                  134 => :defaitiste, # DEFAITISTE
                  135 => :envelocape, # ENVELOCAPE
                  136 => :epine_de_fer, # ÉPINE DE FER
                  137 => :farceur, # FARCEUR
                  138 => :force_sable, # FORCE SABLE
                  139 => :garde_amie, # GARDE AMIE
                  140 => :heavy_metal, # HEAVY METAL
                  141 => :herbivore, # HERBIVORE
                  142 => :illusion, # ILLUSION
                  143 => :imposteur, # IMPOSTEUR
                  144 => :impudence, # IMPUDENCE
                  145 => :infiltration, # INFILTRATION
                  146 => :light_metal, # LIGHT METAL
                  147 => :lunatique, # LUNATIQUE
                  148 => :miroir_magik, # MIROIR MAGIK
                  149 => :mode_transe, # MODE TRANSE
                  150 => :momie, # MOMIE
                  151 => :multiecaille, # MULTIECAILLE
                  152 => :peau_miracle, # PEAU MIRACLE
                  153 => :phobique, # PHOBIQUE
                  154 => :pickpocket, # PICKPOCKET
                  155 => :rage_brulante, # RAGE BRÛLANTE
                  156 => :rage_poison, # RAGE POISON
                  157 => :recolte, # RECOLTE
                  158 => :rege_force, # RÉGÉ-FORCE
                  159 => :sans_limite, # SANS LIMITE
                  160 => :telepathe, # TELEPATHE
                  161 => :tension, # TENSION
                  162 => :tera_voltage, # TERA-VOLTAGE
                  163 => :toxitouche, # TOXITOUCHE
                  164 => :turbo_brasier, # TURBO-BRASIER
                  165 => :victorieux # VICTORIEUX
                }
end